services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true